import polars as pl

L2_SCHEMA = {
    "Code": pl.Utf8,
    "LayerId": pl.Utf8,
    "DeltaRefresh_ServerTimestamp": pl.Utf8,
    "DeltaRefresh_MarketTimestamp": pl.Utf8,
    "DeltaRefresh_DeltaAction": pl.Utf8,
    "DeltaRefresh_Level": pl.Float32,
    "DeltaRefresh_Price": pl.Float32,
    "DeltaRefresh_CumulatedUnits": pl.Float32,
    "DeltaRefresh_NbOrders": pl.Float32,
    "DeltaRefresh_ContinuationFlag": pl.Boolean,
    "DeltaRefresh_OtherValues_TradeExecutionTimestamp": pl.Utf8,
    "DeltaRefresh_OtherValues_TradeID": pl.Utf8,
    "DeltaRefresh_OtherValues_MARKET_TradingStatus": pl.Utf8,
    "DeltaRefresh_OtherValues_LastTradeQty": pl.Float32,
    "DeltaRefresh_OtherValues_LastTradePrice": pl.Float32,
    "DeltaRefresh_OtherValues_LastTradeSide": pl.Utf8,
    "DeltaRefresh_OtherValues_AggressorSide": pl.Utf8,
    "DeltaRefresh_OtherValues_DailyOpeningPrice": pl.Float32,
    "DeltaRefresh_OtherValues_MARKET_GroupTradingStatus": pl.Utf8,
    "DeltaRefresh_OtherValues_MARKET_CME_MatchEventIndicator": pl.Utf8,
    "OverlapRefresh_ServerTimestamp": pl.Utf8,
    "OverlapRefresh_MarketTimestamp": pl.Utf8,
    "OverlapRefresh_BidChangeIndicator": pl.Float32,
    "OverlapRefresh_AskChangeIndicator": pl.Float32,
    "OverlapRefresh_BidLimits": pl.Utf8,
    "OverlapRefresh_AskLimits": pl.Utf8,
    "OverlapRefresh_OtherValues_TradeExecutionTimestamp": pl.Utf8,
    "OverlapRefresh_OtherValues_MARKET_TradingStatus": pl.Utf8,
    "OverlapRefresh_OtherValues_DailyOpeningPrice": pl.Float32,
    "OverlapRefresh_OtherValues_MARKET_GroupTradingStatus": pl.Utf8,
    "OverlapRefresh_OtherValues_LastTradeQty": pl.Float32,
    "OverlapRefresh_OtherValues_LastTradePrice": pl.Float32,
    "OverlapRefresh_OtherValues_TradeID": pl.Utf8,
    "OverlapRefresh_OtherValues_AggressorSide": pl.Utf8,
    "OverlapRefresh_OtherValues_MARKET_CME_MatchEventIndicator": pl.Utf8,
    "MaxVisibleDepth_MaxVisibleDepth": pl.Float32,
}

L1_SCHEMA = {
    'Code': pl.Utf8,
    'ServerTimestamp': pl.Utf8,
    'TradeEvent_MarketTimestamp': pl.Utf8,
    'TradeEvent_LastPrice': pl.Float32,
    'TradeEvent_LastTradeQuantity': pl.Float32,
    'TradeEvent_Flags_OffBookTrade': pl.Utf8,
    'TradeEvent_Context_TradeExecutionTimestamp': pl.Utf8,
    'TradeEvent_Context_TradeID': pl.Utf8,
    'TradeEvent_Context_AggressorSide': pl.Utf8,
    'TCC_Flags_IsCorrection': pl.Utf8,
    'TCC_Flags_IsFromVenue': pl.Utf8,
    'TCC_Flags_IsOffBookTrade': pl.Utf8,
    'TCC_OriginalTrade_Price': pl.Utf8,
    'TCC_OriginalTrade_Quantity': pl.Utf8,
    'TCC_OriginalTrade_ImpactIndicator': pl.Utf8,
    'TCC_OriginalTrade_MarketTimestamp': pl.Utf8,
    'TCC_OriginalTrade_TradeId': pl.Utf8,
    'TCC_CorrectedTrade_Price': pl.Utf8,
    'TCC_CorrectedTrade_Quantity': pl.Utf8,
    'TCC_CorrectedTrade_ImpactIndicator': pl.Utf8,
    'TCC_CorrectedTrade_MarketTimestamp': pl.Utf8,
    'TCC_CorrectedTrade_TradeId': pl.Utf8,
}